package rules.cep;
//dialect  "mvel"

import com.ftn.sbnz.backward.model.events.BluffEvent;
import com.ftn.sbnz.backward.model.models.Player;
import com.ftn.sbnz.backward.model.models.PlayerProfile;

rule "Detect Frequent Bluffer"
when
    $player : Player($id : id, profile.profileType == "UNKNOWN")
    Number(intValue >= 3) from accumulate(
        BluffEvent(playerId == $id) over window:time(5m) from entry-point "player-actions",
        count()
    )
then
    PlayerProfile profile = new PlayerProfile("FREQUENT_BLUFFER", 0.5);
    $player.setProfile(profile);
    insert(profile);
    update($player)
    System.out.println("Player " + $id + " classified as frequent bluffer");
end
